### ISSUE TITLE
Duplicate middleware name 'NewRelicHeader' error on nest.js platform when running aws-sdk commands

### ISSUE THREAD

**Issue by LykinsN** [newrelic/node-newrelic-aws-sdk#213] opened 2023-10-23 13:43 UTC
## Description

Our team is running a nest.js implementation that leverages the AWS SDK, specifically with DynamoDB integration, and we've recently attempted to add New Relic instrumentation. We've tried both the `import 'newrelic'` method, as well as adding the command line arguments to our node invocation: `node --experimental-loader newrelic/esm-loader.mjs -r newrelic app.js` and in both cases, the instrumentation works and we can see metrics being streamed to our dashboard.

However, whenever we enter a code path that leverages an AWS SDK command, we receive the `Duplicate middleware name 'NewRelicHeader'` error.

Ex: `sendQueryCommand: exception; Duplicate middleware name 'NewRelicHeader'`

We're running other similar tooling but do not experience the same failure. Unfortunately, since this code is all proprietary, I'm not sure how much more context I can share. 

## Expected Behavior

The AWS SDK should execute its logic without any issues.

## Steps to Reproduce

Enter a code path where an AWS SDK command is being executed, in a workspace where the tooling is driven by nest.js and has New Relic instrumentation in place.

## Your Environment

Ubuntu 20.04
Node 18.16.0
node_modules/@aws-sdk/client-dynamodb: 3.429.0
node_modules/@aws-sdk/lib-dynamodb: 3.429.0
node_modules/@newrelic/aws-sdk: 7.0.1
node_modules/newrelic: 11.2.1

## Additional context

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by mrickard** [comment] 2023-10-23 14:05
@LykinsN I'm sorry to hear that you're having trouble. We've seen other reports of this. We haven't yet been able to reproduce it, and we haven't received any reproduction cases. While your application is proprietary, is it possible that you could provide a simple app with these dependencies showing the same behavior?

**Comment by bizob2828** [comment] 2023-10-24 16:29
This is a duplicate of #211. If you can provide us a reproduction case, that'll greatly help. Please post it in #211 if you get to it.

**Closed by bizob2828** 2023-10-24 16:29 UTC
Labels: bug, needs-triage

**Comment by LykinsN** [comment] 2023-10-25 13:02
Unfortunately, we don't have a way to reproduce the issue in isolation. Our platform is a full-stack app with a lot of external dependencies, so it'd be a heavy lift to scale everything down, to the point that it could be run in a sandbox environment.
