### ISSUE TITLE
Duplicate middleware name NewRelicDynamoDocClientMiddleware

### ISSUE THREAD

**Issue by suryajak** [newrelic/node-newrelic-aws-sdk#144] opened 2022-09-05 16:02 UTC
This layer is breaking our lambda using NodeJS14x runtime and deployed in  us-west-2. :

```
"errorMessage": "Duplicate middleware name 'NewRelicDynamoDocClientMiddleware'",
  "trace": [
    "CustomError: Duplicate middleware name 'NewRelicDynamoDocClientMiddleware'",
    "    at /var/task/src/app.js:1:42462",
    "    at U (/var/task/src/app.js:1:42477)",
    "    at Y (/var/task/src/app.js:1:42568)",
    "    at Runtime.V (/var/task/src/app.js:1:43593)",
    "    at /opt/nodejs/node_modules/newrelic/lib/shim/shim.js:1313:22",
    "    at LegacyContextManager.runInContext (/opt/nodejs/node_modules/newrelic/lib/context-manager/legacy-context-manager.js:59:23)",
    "    at TransactionShim.applySegment (/opt/nodejs/node_modules/newrelic/lib/shim/shim.js:1303:25)",
    "    at Runtime.wrappedHandler (/opt/nodejs/node_modules/newrelic/lib/serverless/aws-lambda.js:186:20)",
    "    at /opt/nodejs/node_modules/newrelic/lib/shim/shim.js:1313:22",
    "    at LegacyContextManager.runInContext (/opt/nodejs/node_modules/newrelic/lib/context-manager/legacy-context-manager.js:59:23)"
    
```

This is the relevant yml config:

```
 newRelic:
    accountId: ${env:NR_ACCOUNTID}
    apiKey: ${env:NR_LICENSE_KEY}
    enableExtensionLogs: false 
    enableIntegration: true     
```

What am I missing?

**Comment by bizob2828** [comment] 2022-09-06 14:45
@suryajak this is a duplicate of #130.  As you can see in the comment stream, I couldn't reproduce it when it was originally logged.  

It would be very helpful if you could provide a code snippet to reproduce the error.  It doesn't need to be a lambda function as that bit is unrelated but just the code where you are defining multiple dynamo doc client instances I think.  Also which versions of `@aws-sdk/lib-dynamodb` and `@newrelic/aws-sdk` are getting installed?

**Comment by suryajak** [comment] 2022-09-08 05:04
Here are the versions that you were looking for:

    "@aws-sdk/lib-dynamodb": "^3.137.0",
     "serverless-newrelic-lambda-layers": "^3.3.5",
     
I am not aware of multiple ddb client instances

**Comment by bizob2828** [comment] 2022-09-08 13:37
Hi @suryajak we will need steps to reproduce the error. You can see the details of attempts to reproduce in #130. If you're not comfortable sharing that here you can, I recommend leveraging our support team over at support.newrelic.com which can help deep-dive into solving the problem. They will also ask to collect the necessary information which may or may not be sensitive (such as logs).

**Closed** 2022-10-05 21:06 UTC
Labels: bug, support
