### ISSUE TITLE
Expose new relic core module

### ISSUE THREAD

**Issue by sleistner** [newrelic/node-newrelic-aws-sdk#25] opened 2019-12-04 08:48 UTC
It'll be great if the underlying new relic base module would be exposed by this module in order to be able importing it in one go.

e.g.

```javascript
const newrelic = require('@newrelic/aws-sdk')
```

**Comment by michaelgoin** [comment] 2020-01-06 21:31
Hi @sleistner,

Thank you for the suggestion! Flagging this as a feature request for consideration.

**Comment by rr0214** [comment] 2021-11-10 21:32
The large sizing indicates doing this across all instrumentation packages that aren't plugins

**Comment by bizob2828** [comment] 2023-05-01 15:12
I'm going to close this as we will no longer support these packages as standalone due to limitations of agent in v10.  We will be shutting off standalone access in here https://github.com/newrelic/node-newrelic/issues/1601.  In fact if you use this package with v10 of the agent it will exhibit unintended behavior by loading hooks multiple times

**Closed by bizob2828** 2023-05-01 15:12 UTC
Labels: feature-request, size: large, dnm2j, sync2jira
