### ISSUE TITLE
v10 Newrelic causes issue with aws-s3 sdk in some cases

### ISSUE THREAD

**Issue by JoelV** [newrelic/node-newrelic-aws-sdk#181] opened 2023-04-20 15:12 UTC
## Description

Upon upgrading to newrelic@10, and endpoint that where we make calls to aws using the aws-sdk  gave an error.

## Expected Behavior

The above does not happen

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

```
message:Duplicate middleware name 'NewRelicHeader'
```
Trace
```
"Error: Duplicate middleware name 'NewRelicHeader'\n    at Object.add (/opt/node_modules/@aws-sdk/client-s3/node_modules/@aws-sdk/middleware-stack/dist-cjs/MiddlewareStack.js:130:31)\n    at Object.applyToStack (/opt/node_modules/@newrelic/aws-sdk/lib/v3/smithy-client.js:33:19)\n    at Object.use (/opt/node_modules/@aws-sdk/client-s3/node_modules/@aws-sdk/middleware-stack/dist-cjs/MiddlewareStack.js:167:20)\n    at S3Client.wrapShim (/opt/node_modules/@newrelic/aws-sdk/lib/v3/util.js:33:26)\n    at new WrappedClass (/opt/node_modules/newrelic/lib/shim/shim.js:2064:30)\n    at new S3Client (/opt/node_modules/@aws-sdk/client-s3/dist-cjs/S3Client.js:31:9)\n    at ProcessStatus.<anonymous> (/opt/app/helpers/s3-client.js:87:24)\n    at Generator.next (<anonymous>)\n    at /opt/app/helpers/s3-client.js:8:71\n    at new Promise (<anonymous>)"
```

## Steps to Reproduce
1. make endpoint with hapi that makes a call out to aws s3 to get presigned urls
2. make a call to the endpoint and it fails

## Your Environment

Node version: 17.3.0
Operating System and version: Alpine 3.1.3 Linux
Web Framework: Hapi

**Comment by bizob2828** [comment] 2023-04-20 15:30
What's probably happening @JoelV is that you're loading either the agent twice, or the agent + the @newrelic/aws-sdk instrumentation a 2nd time.  In v10.0.0 of the agent we support registering multiple instrumentation hooks. We have protections around double loading agents but it has changed a lot recently so I would inspect your entire application dep tree and ensure that you have only one agent loading.  If you have 2 and you can't control that make sure they're on the same version.

**Comment by JoelV** [comment] 2023-04-20 17:08
Ok we will look into that and let you know

**Comment by bizob2828** [comment] 2023-04-20 17:54
@JoelV yes a reproduction of the issue would be helpful because I cannot reproduce

**Comment by JoelV** [comment] 2023-04-21 21:18
index.js

```
const dotenv = require('dotenv');
dotenv.config();
require('newrelic')
const Hapi = require('@hapi/hapi');
const { S3, GetObjectCommand } = require('@aws-sdk/client-s3');
const { getSignedUrl } = require('@aws-sdk/s3-request-presigner');

const init = async () => {

    const server = Hapi.server({
        port: 3000,
        host: 'localhost'
    });

    server.route({
      method: 'GET',
      path: '/aws',
      handler: async () => {
        try {
          const DefaultParams = {
            region: 'us-west-2',
            credentials: { accessKeyId: process.env.AWS_ACCESS_KEY, secretAccessKey: process.env.AWS_SECRET },
          };


          const commandParams = {
            Bucket: process.env.OUTPUT_BUCKET,
            Key: 'somfile.text',
          };
          const command = new GetObjectCommand(
            commandParams,
          );
          const client1 = new S3(DefaultParams);
          const result = await getSignedUrl(client1, command, { expiresIn: 3600 });
          console.log(result);
        return 'Hello World!';
        } catch (err) {
          console.log(err);
        }
      }
  });

    await server.start();
    console.log('Server running on %s', server.info.uri);
};

process.on('unhandledRejection', (err) => {

    console.log(err);
    process.exit(1);
});

init();
```
package.json
```
{
  "dependencies": {
    "@aws-sdk/client-s3": "^3.118.1",
    "@aws-sdk/s3-request-presigner": "^3.317.0",
    "@hapi/hapi": "^21.3.1",
    "dotenv": "^16.0.3",
    "newrelic": "^10.0.0"
  }
}
```

**Comment by bizob2828** [comment] 2023-04-25 17:10
Thanks @JoelV I will take a look and get back to you!

**Comment by bizob2828** [comment] 2023-04-27 16:07
@JoelV I cannot reproduce with your sample above.  In fact it creates the relevant hapi span.  No aws spans because you aren't doing anything in this example that we instrument.  You mention in the example is fails when calling `new S3`.  I still suspect you have multiple copies of the agent running.


<img width="1516" alt="screenshot 2023-04-27 at 12 05 19 PM" src="https://user-images.githubusercontent.com/1874937/234920959-67ad3a2f-7179-4ec5-a895-f99238536319.png">

For issues like this, I recommend leveraging our support team over at [support.newrelic.com](https://support.newrelic.com) which can help deep-dive into solving the problem. They will also ask to collect the necessary information which may or may not be sensitive (such as logs). I'm going to go ahead and close this. If you can provide more concrete steps in the above example, feel free to reopen.

**Comment by JoelV** [comment] 2023-04-27 16:26
@bizob2828 

Can you try reproducing with these deps. I've version locked the aws depedencies

```
{
  "dependencies": {
    "@aws-sdk/client-s3": "^3.118.1",
    "@aws-sdk/s3-request-presigner": "^3.317.0",
    "@hapi/hapi": "^21.3.1",
    "dotenv": "^16.0.3",
    "newrelic": "^10.0.0"
  }
}
```

**Comment by bizob2828** [comment] 2023-04-27 17:13
Anything after 3.316.0 fixes this. I see the issue but I'm not sure of the best solution now that version 10 of the agent registers instrumentation n times

**Comment by bizob2828** [comment] 2023-04-27 18:08
I'm going to close this as won't fix.  The issue here is that you have to make sure you have the same versions of all `@aws-sdk` scoped packages.  Otherwise we handle different versions of `@aws-sdk/smith-client` as separate modules.  Since version 10 we allow registering multiple instrumentation hooks which is what's at play right now.  We have plans to make this more resilient in the future but the workaround I just provided is our stance for now. I apologize for the confusion and toil.

**Comment by bizob2828** [comment] 2023-04-27 18:53
Sorry for the back and forth. I have a workaround that will make this function well

**Comment by JoelV** [comment] 2023-04-27 19:04
@bizob2828 Thank you for the clear communication!!

**Comment by bizob2828** [comment] 2023-05-01 16:06
@JoelV 5.0.5 of @newrelic/aws-sdk should fix this.

**Comment by ChaseMarcum** [comment] 2023-05-31 20:43
@bizob2828 I work in the same team as @JoelV and this issue was resolved for us when we were using aws-sdk v3.338.0. With the latests versions for aws-sdk v3.341.0 and v3.342.0 the `Duplicate middleware name 'NewRelicHeader'` error has resurfaced. We are currently new using the newrelic v10.1.2 library.

For the meantime reverting back to aws-sdk v3.338.0 temporary resolves the issue.

**Comment by JoelV** [comment] 2023-06-02 20:12
@jmartin4563 

I work with @ChaseMarcum  and originally brought up the issue. Here's the hapi script that reproduces the issue. Note you will have to use the attached package-lock.json to reproduce the issue. It's reflective of the state of the node_modules directory in the application that we see the error in.

index.js
```
const dotenv = require('dotenv');
dotenv.config(); 
require('newrelic');
const Hapi = require('@hapi/hapi');
const { SQSClient, SendMessageCommand } = require("@aws-sdk/client-sqs"); 

const init = async () => {
  const server = Hapi.server({
    port: 3000,
    host: 'localhost'
  });

  server.route({
    method: 'GET',
    path: '/aws',
    handler: async (request, h) => {
      try {
       
        const sqs = new SQSClient({ region: 'us-west-2' }); //this is where it throws the duplicate header error
        const message = {
          MessageBody: JSON.stringify({ ok: true}),
          QueueUrl: process.env.QUEUE_NAME,
        }
        const resultSQS = await sqs.send(new SendMessageCommand(message))
        console.log(resultSQS);
        return 'Hello World!';
      } catch(error){
        console.log(error);
        throw error
      }
    }
  });
 

  await server.start();
  console.log('Server running on %s', server.info.uri);
};

process.on('unhandledRejection', (err) => {
  console.log(err);
  process.exit(1);
});

init();
```
package.json
```
{
  "dependencies": {
    "@aws-sdk/client-sqs": "3.344.0",
    "@hapi/hapi": "^21.0.0",
    "dotenv": "^16.0.0",
    "newrelic": "^10.1.2"
  }
}
```

/Users/joelvillahermosa/code/NODE/lab/hapi-newrelic-aws/package-lock.json

**Comment by jmartin4563** [comment] 2023-06-05 18:41
@JoelV: it looks the lockfile you provided still has `@newrelic/aws-sdk` version 5.0.2 in it. If you `npm uninstall newrelic` and `npm install newrelic` you should get an updated lockfile entry without having to regenerate the entire lockfile. I did this with your example and no longer see the issue.

**Closed** 2023-06-05 21:26 UTC
Labels: bug, needs-triage
