### ISSUE TITLE
Duplicate middleware name 'NewRelicHeader'

### ISSUE THREAD

**Issue by skmichaeldavis** [newrelic/node-newrelic-aws-sdk#175] opened 2023-03-22 18:33 UTC
## Description

When running my application, I'm encountering startup crashes due to duplicate "smithy" injected middlewares in the AWS SDK by the Newrelic AWS Agent.  This seems to be specific to using the newrelic agent in both my main package and a library package.  

## Expected Behavior

No "Duplicate middleware" exception

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

I see a pair of calls to:

    add (root/Library/node_modules/s3-streamlogger/node_modules/@aws-sdk/middleware-stack/dist-cjs/MiddlewareStack.js:120)    
    applyToStack (root/Main/node_modules/@newrelic/aws-sdk/lib/v3/smithy-client.js:33)    
    use (root/Library/node_modules/s3-streamlogger/node_modules/@aws-sdk/middleware-stack/dist-cjs/MiddlewareStack.js:167)    
    wrapShim (root/Main/node_modules/@newrelic/aws-sdk/lib/v3/util.js:33)    
    WrappedClass (root/Main/node_modules/newrelic/lib/shim/shim.js:2048)    
    WrappedClass (root/Library/node_modules/newrelic/lib/shim/shim.js:2047)    
    S3Client (root/Library/node_modules/s3-streamlogger/node_modules/@aws-sdk/client-s3/dist-cjs/S3Client.js:31)    
    S3StreamLogger (root/Library/node_modules/s3-streamlogger/index.js:69)    
    Logger (root/Library/lib/Logger/loggers/newrelic-s3.js:16)    

then immediately it tries doing another pair of calls to:

    add (root/Library/node_modules/s3-streamlogger/node_modules/@aws-sdk/middleware-stack/dist-cjs/MiddlewareStack.js:120)
    applyToStack (root/Library/node_modules/@newrelic/aws-sdk/lib/v3/smithy-client.js:33)
    use (root/Library/node_modules/s3-streamlogger/node_modules/@aws-sdk/middleware-stack/dist-cjs/MiddlewareStack.js:167)
    wrapShim (root/Library/node_modules/@newrelic/aws-sdk/lib/v3/util.js:33)
    WrappedClass (root/Library/node_modules/newrelic/lib/shim/shim.js:2048)
    S3Client (root/Library/node_modules/s3-streamlogger/node_modules/@aws-sdk/client-s3/dist-cjs/S3Client.js:31)
    S3StreamLogger (root/Library/node_modules/s3-streamlogger/index.js:69)
    Logger (root/Library/lib/Logger/loggers/newrelic-s3.js:16)

Note the two versions of WrappedClass in the first trace but only one in the second.

Which results in

    Error: Duplicate middleware name 'NewRelicHeader'
        at Object.add (root/Library/node_modules/s3-streamlogger/node_modules/@aws-sdk/middleware-stack/dist-cjs/MiddlewareStack.js:130:31)
        at Object.applyToStack (root/Library/node_modules/@newrelic/aws-sdk/lib/v3/smithy-client.js:33:19)

## Steps to Reproduce

Library project that uses "@newrelic/winston-enricher": "4.0.1", and "s3-streamlogger": "1.9.0",

Main project that uses Library as a dependency and also uses "newrelic": "9.11.0",

Main project calls `require("newrelic")` then later invokes Library's logger code, logger code creates a Newrelic Winston Logger then also tries creating an S3StreamLogger (which errors).  Main project also creates an S3 Client but that doesn't appear to be related

## Your Environment

* Browser name and version: N/A
* Node version: 14+
* Operating System and version: Linux various

## Additional context

This configuration worked on previous versions of Newrelic agent, issue only occurs when upgrading from 6.X to 9.11.   

The Library project contains common logging code that is used in multiple services, so it needs to have the winston-enricher library (which brings in the main newrelic library).  And of course the Main project contains my main entrypoint and business logic so it needs the main newrelic agent.  So I don't see any way around having the newrelic as a dependency in both places.

It seems like adding the "override" flag to smithy-client's call to .add would solve my issue

**Comment by bizob2828** [comment] 2023-03-22 18:38
Hi @skmichaeldavis we've seen this report before in #130 and #144.  We couldn't reproduce and when asking the reporters to provide reproduction cases, it went silent.  Can you provide a reproduction case for us to triage?

**Comment by skmichaeldavis** [comment] 2023-03-23 15:31
@bizob2828 I reproduced the bug in https://github.com/skmichaeldavis/newrelic-node-bug-example

**Comment by bizob2828** [comment] 2023-03-23 16:58
I'm going to close this.  The work will be tracked in https://github.com/newrelic/node-newrelic/issues/1565

**Closed by bizob2828** 2023-03-23 16:58 UTC
Labels: bug, needs-triage

**Comment by skmichaeldavis** [comment] 2023-03-23 17:21
The NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED was just a leftover from the sample I forked from.  My actual application uses the explicit winston logger.  I'll take a look if that new built-in functionality can work as a replacement but lack of control over the newrelic logger will probably be an issue as we have multiple loggers with different formats/level settings.

Looking forward to the fix in 1565 @bizob2828

**Comment by bizob2828** [comment] 2023-03-23 17:32
@skmichaeldavis I doubt you'll need the @newrelic/winston-logenricher, but let me know

**Comment by skmichaeldavis** [comment] 2023-03-24 13:55
@bizob2828  I can confirm upgrading to 9.14.1 fixes the issue without any other changes.  Thanks so much!

**Comment by klosowsk** [comment] 2023-03-28 04:11
Still getting the issue after upgrading to 9.14.1

<img width="1468" alt="image" src="https://user-images.githubusercontent.com/12361879/228125940-fe4b7075-6489-4ec3-adae-202b193216a2.png">

**Comment by bizob2828** [comment] 2023-03-28 13:29
@klosowsk a couple of questions: do you have multiple versions of the newrelic agent in your application? If so, they all have to be on 9.14.1.  Can you provide a reproduction case?
